import { Inter } from 'next/font/google'
import Script from 'next/script'

// Import Css Files
import '../public/assets/css/style.css'
import '../public/assets/vendor/bootstrap-select/dist/css/bootstrap-select.min.css'
import '../public/assets/vendor/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.css'
import '../public/assets/vendor/swiper/swiper-bundle.min.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Viyaga Meat',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Meta */}
        <meta name="theme-color" content="#009688" />
        <meta name="author" content="VIYAGA" />
        <meta name="robots" content="index, follow" />
        <meta
          name="keywords"
          content="meat, chicken, mutton, fish, sea food, ui kit, multiple color, dark layout, meat shop"
        />
        <meta
          property="og:image"
          content="https://w3meat.dexignzone.com/xhtml/social-image.png"
        />
        <meta name="format-detection" content="telephone=no" />
        {/* PWA Version */}
        <link rel="manifest" href="/manifest.json" />
      </head>
      <body className={inter.className} suppressHydrationWarning={true} >

        {children}
        <Script src='/assets/js/jquery.js' strategy="beforeInteractive" />
        <Script src='/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' strategy="beforeInteractive" />
        <Script src='/assets/vendor/swiper/swiper-bundle.min.js' strategy="beforeInteractive" />
        <Script src='/assets/vendor/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js' strategy="lazyOnload" />
        <Script src='/assets/js/dz.carousel.js' strategy="lazyOnload" />
        <Script src='/assets/vendor/wow/dist/wow.min.js' strategy="lazyOnload" />
        <Script src='/assets/js/settings.js' strategy="lazyOnload" />
        <Script src='/assets/js/custom.js' strategy="lazyOnload" />
      </body>
    </html>
  )
}
